CREATE DATABASE WebSiteBanHang

USE WebSiteBanHang


CREATE TABLE NhaSanXuat
(
	MaNSX VARCHAR(100) PRIMARY KEY,
	TenNSX NVARCHAR(100),
	ThongTin NVARCHAR(255),
	Logo NVARCHAR(MAX)
)

CREATE TABLE NhaCungCap
(
	MaNCC VARCHAR(100) PRIMARY KEY,
	TenNCC NVARCHAR(100),
	DiaChi NVARCHAR(255),
	Email NVARCHAR(255),
	SoDienThoai VARCHAR(10),
	Fax NVARCHAR(50)
)

CREATE TABLE PhieuNhap
(
	MaPN VARCHAR(100) PRIMARY KEY,
	MaNCC VARCHAR(100),
	NgayNhap DATETIME,
	DaXoa bit,

	CONSTRAINT[FK_PhieuNhap_NhaCungCap] FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC) ON DELETE CASCADE
)

CREATE TABLE LoaiThanhVien
(
	MaLoaiTV VARCHAR(100) PRIMARY KEY,
	TenLoai NVARCHAR(50),
	UuDai INT
)

CREATE TABLE ThanhVien
(
	MaThanhVien VARCHAR(100) PRIMARY KEY,
	TaiKhoan NVARCHAR(100),
	MatKhau NVARCHAR(100),
	HoTen NVARCHAR(100),
	DiaChi NVARCHAR(255),
	Email NVARCHAR(255),
	SoDienThoai VARCHAR(10),
	CauHoi NVARCHAR(MAX),
	CauTraLoi NVARCHAR(MAX),
	MaLoaiTV VARCHAR(100)

	CONSTRAINT[FK_ThanhVien_LoaiThanhVien] FOREIGN KEY (MaLoaiTV) REFERENCES LoaiThanhVien(MaLoaiTV)
)

CREATE TABLE KhachHang
(
	MaKH VARCHAR(100) PRIMARY KEY,
	TenKH NVARCHAR(100),
	DiaChi NVARCHAR(255),
	Email NVARCHAR(255),
	SoDienThoai VARCHAR(10),
	MaThanhVien VARCHAR(100)

	CONSTRAINT[FK_KhachHang_ThanhVien] FOREIGN KEY (MaThanhVien) REFERENCES ThanhVien(MaThanhVien) ON DELETE CASCADE
)

CREATE TABLE ChatLieu
(
	MaChatLieu INT IDENTITY PRIMARY KEY,
	TenChatLieu NVARCHAR(50)
)

CREATE TABLE MauSac
(
	MaMauSac INT IDENTITY PRIMARY KEY,
	TenMauSac NVARCHAR(50)
)

CREATE TABLE KichCo
(
	MaSize INT IDENTITY PRIMARY KEY,
	TenSize NVARCHAR(3)
)

CREATE TABLE LoaiSanPham
(
	MaLoaiSP VARCHAR(100) PRIMARY KEY,
	TenLoai NVARCHAR(100),
	Icon NVARCHAR(255),
	BiDanh NVARCHAR(50)
)

CREATE TABLE SanPham
(
	MaSP VARCHAR(100) PRIMARY KEY,
	TenSP NVARCHAR(255),
	DonGia DECIMAL(18,0),
	NgayCapNhat DATETIME,
	CauHinh NVARCHAR(MAX),
	MoTa NVARCHAR(MAX),
	HinhAnh NVARCHAR(MAX),
	SoLuongTon INT,
	LuotXem INT,
	LuotBinhChon INT,
	LuotBinhLuan INT,
	SoLanMua INT,
	Moi INT,
	MaNCC VARCHAR(100),
	MaNSX VARCHAR(100),
	MaLoaiSP VARCHAR(100),
	MaChatLieu INT,
	MaMauSac INT,
	MaSize INT,
	DaXoa BIT

	CONSTRAINT[FK_SanPham_NhaCungCap] FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
	CONSTRAINT[FK_SanPham_NhaSanXuat] FOREIGN KEY (MaNSX) REFERENCES NhaSanXuat(MaNSX),
	CONSTRAINT[FK_SanPham_LoaiSanPham] FOREIGN KEY (MaLoaiSP) REFERENCES LoaiSanPham(MaLoaiSP),
	CONSTRAINT[FK_SanPham_ChatLieu] FOREIGN KEY (MaChatLieu) REFERENCES ChatLieu(MaChatLieu),
	CONSTRAINT[FK_SanPham_MauSac] FOREIGN KEY (MaMauSac) REFERENCES MauSac(MaMauSac),
	CONSTRAINT[FK_SanPham_KichCo] FOREIGN KEY (MaSize) REFERENCES KichCo(MaSize)
)

CREATE TABLE ChiTietPhieuNhap
(
	MaChiTietPN VARCHAR(100) PRIMARY KEY,
	MaPN VARCHAR(100),
	MaSP VARCHAR(100),
	DonGiaNhap DECIMAL(18,0),
	SoLuongNhap INT

	CONSTRAINT[FK_ChiTietPhieuNhap_PhieuNhap] FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN),
	CONSTRAINT[FK_ChiTietPhieuNhap_SanPham] FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),

)

CREATE TABLE DonDatHang
(
	MaDDH VARCHAR(100) PRIMARY KEY,
	NgayDat DATETIME,
	TinhTrangGiaoHang BIT,
	NgayGiao DATETIME,
	DaThanhToan BIT,
	MaKH VARCHAR(100),
	UuDai INT

	CONSTRAINT[FK_DonDatHang_KhachHang] FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
)

CREATE TABLE ChiTietDonDatHang
(
	MaChiTietDDH VARCHAR(100) PRIMARY KEY,
	MaDDH VARCHAR(100),
	MaSP VARCHAR(100),
	TenSP NVARCHAR(255),
	SoLuong INT,
	DonGia DECIMAL(18,0)

	CONSTRAINT[FK_ChiTietDonDatHang_DonDatHang] FOREIGN KEY (MaDDH) REFERENCES DonDatHang(MaDDH),
	CONSTRAINT[FK_ChiTietDonDatHang_SanPham] FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
)

CREATE TABLE BinhLuan 
(
	MaBL INT IDENTITY PRIMARY KEY,
	NoiDungBL NVARCHAR(MAX),
	MaThanhVien VARCHAR(100),
	MaSP VARCHAR(100)

	CONSTRAINT[FK_BinhLuan_ThanhVien] FOREIGN KEY (MaThanhVien) REFERENCES ThanhVien(MaThanhVien),
	CONSTRAINT[FK_BinhLuan_SanPham] FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
)


